python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 0     --num_iterations 1    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 0     --num_iterations 2    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 0     --num_iterations 3    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 0     --num_iterations 4    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 0     --num_iterations 5    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 1     --num_iterations 1    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 1     --num_iterations 2    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 1     --num_iterations 3    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 1     --num_iterations 4    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 1    --brf_batch_remove 1     --num_iterations 5    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 0     --num_iterations 1    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 0     --num_iterations 2    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 0     --num_iterations 3    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 0     --num_iterations 4    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 0     --num_iterations 5    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 1     --num_iterations 1    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 1     --num_iterations 2    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 1     --num_iterations 3    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 1     --num_iterations 4    --dataset mutag
python run_graph_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 2    --brf_batch_remove 1     --num_iterations 5    --dataset mutag
