python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 10    --brf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 20    --brf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 30    --brf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring brf     --layer_type GCN    --num_trials 10    --device cuda:0    --brf_batch_add 50    --brf_batch_remove 30     --num_iterations 3
