python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GCN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 25    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 50    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 75    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 100    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 125    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 150    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 175    --dataset ogbn-arxiv
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset pubmed
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset squirrel
python run_node_classification.py     --rewiring fosr     --layer_type GIN    --num_trials 100    --device cuda:0    --num_iterations 200    --dataset ogbn-arxiv
